import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "strongpass",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/icons/favicon-16x16.png", sizes: "16x16" },
      { url: "/icons/favicon-32x32.png", sizes: "32x32" },
      { url: "/icons/favicon-96x96.png", sizes: "96x96" },
      { url: "/icons/android-icon-192x192.png", sizes: "192x192" },
    ],
    apple: [
      { sizes: "57x57", url: "/icons/apple-icon-57x57.png" },
      { sizes: "60x60", url: "/icons/apple-icon-60x60.png" },
      { sizes: "72x72", url: "/icons/apple-icon-72x72.png" },
      { sizes: "76x76", url: "/icons/apple-icon-76x76.png" },
      { sizes: "114x114", url: "/icons/apple-icon-114x114.png" },
      { sizes: "120x120", url: "/icons/apple-icon-120x120.png" },
      { sizes: "144x144", url: "/icons/apple-icon-144x144.png" },
      { sizes: "152x152", url: "/icons/apple-icon-152x152.png" },
      { sizes: "180x180", url: "/icons/apple-icon-180x180.png" },
    ],
  },
  manifest: "/icons/manifest.json",
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="py-5 container max-w-[1300px] mx-auto flex flex-col w-full h-screen">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}

